## 1. Write a Python Program to Add two Matrices ?


In [10]:
def addMatrix(a, b):
    print(f"input : {a}, {b}")
    output = []
    if len(a) == len(b):
        for ele in range(len(a)):
            if len(a[ele]) == len(b[ele]):
                output.append([])
                for sub_ele in range(len(a[ele])):
                    output[ele].append(a[ele][sub_ele] + b[ele][sub_ele])
        
            else:
                print("length of row and column should be same")
    else:
        print("length of two matrics should be equal")
    print(f"output : {output}")
   

In [11]:
addMatrix([[1,2,3],[4,5,6],[7,8,9]], [[9,8,7],[6,5,4],[3,2,1]])

input : [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[9, 8, 7], [6, 5, 4], [3, 2, 1]]
output : [[10, 10, 10], [10, 10, 10], [10, 10, 10]]


In [13]:
## using numpy
import numpy as np
matrix_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix_2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]
sum_matrix = np.add(matrix_1, matrix_2)
sum_matrix

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

## 2. Write a Python Program to Multiply two Matrices ?


In [18]:
def mulMatrix(a, b):
    output = []
    if len(a) == len(b):
        for ele in range(len(a)):
            if len(a[ele]) == len(b[ele]):
                output.append([])
                for sub_ele in range(len(a[ele])):
                    output[ele].append(a[ele][sub_ele] * b[ele][sub_ele])
            else:
                print("length of matrics must be same")
    else:
        print(f"length of matrics must be same")
    print(f"output : {output}")

In [19]:
mulMatrix([[1,2,3],[4,5,6],[7,8,9]], [[9,8,7],[6,5,4],[3,2,1]])

output : [[9, 16, 21], [24, 25, 24], [21, 16, 9]]


In [20]:
## using numpy
multiply = np.multiply(matrix_1, matrix_2)
multiply

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

## 3. Write a Python Program to transpose a Matrix ?


In [23]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = [[1,2],[4,5],[7,8]]
c = [[1,2,3],[4,5,6]]


In [29]:
def generate_transpose(in_matrix):
    out_matrix = []
    for ele in range(len(in_matrix[0])):
        out_matrix.append([0 for i in range(len(in_matrix))])
    for i in range(len(in_matrix)):
        for j in range(len(in_matrix[i])):
            out_matrix[j][i] = in_matrix[i][j]
    print(f'{in_matrix} -> {out_matrix}')
        
generate_transpose(a)
generate_transpose(b)
generate_transpose(c)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] -> [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
[[1, 2], [4, 5], [7, 8]] -> [[1, 4, 7], [2, 5, 8]]
[[1, 2, 3], [4, 5, 6]] -> [[1, 4], [2, 5], [3, 6]]


In [30]:
## using np
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## 4. Write a Python Program to sort Words in an Alphabatical Order ?


In [34]:
def sortedString():
    in_string = input("Enter string :").title()
    sorted_list = sorted(in_string.split(" "))
    print(" ".join(sorted_list))
sortedString()

Enter string :machine_learning nlp deep_learning computer_vision odoo
Computer_Vision Deep_Learning Machine_Learning Nlp Odoo


## 5. Write a Python Program to remove Punctuations From a String ?


In [35]:
def removePunctuatuions():
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    in_string = input('Enter a String: ')
    out_string = ''
    for ele in in_string:
        if ele not in punctuations:
            out_string += ele
    print(out_string)
removePunctuatuions()

Enter a String: "Full Stacks DS" @ Ineuron 
Full Stacks DS  Ineuron 
